import { defineConfig } from 'oxlint';

export default defineConfig({
  categories: {
    correctness: 'error',
    perf: 'error',
    style: 'error',
    suspicious: 'error',
  },
  env: {
    builtin: true,
  },
  globals: {},
  ignorePatterns: ['dist', '*.md'],
  plugins: undefined,
  rules: {
    complexity: ['error', { max: 30 }],
    'func-names': 'off',
    'jsdoc/check-property-names': 'error',
    'jsdoc/check-tag-names': 'error',
    'jsdoc/require-param': 'error',
    'jsdoc/require-param-description': 'error',
    'jsdoc/require-returns': 'error',
    'jsdoc/require-returns-description': 'error',
    'func-style': 'off',
    'id-length': 'off',
    'init-declarations': 'off',
    'max-depth': ['error', { max: 8 }],
    'max-lines': ['error', { max: 800, skipBlankLines: true, skipComments: true }],
    'max-lines-per-function': ['error', { max: 160, skipBlankLines: true, skipComments: true }],
    'max-params': ['error', { max: 4 }],
    'max-statements': 'off',
    'no-await-in-loop': 'off',
    'no-continue': 'off',
    'no-magic-numbers': 'off',
    'no-nested-ternary': 'off',
    'no-ternary': 'off',
    'no-use-before-define': ['error', { functions: false }],
    'prefer-destructuring': 'off',
    'prefer-for-of': 'off',
    'prefer-template': 'off',
    'prefer-ternary': 'off',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'unicorn/no-nested-ternary': 'off',
  },
});
